[build]
  command = "npm -C frontend ci && npm -C frontend run build"
  publish = "frontend/dist"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
